services:
  # --- 1. INFRAESTRUTURA: CLUSTER CONSUL (PERFIL: "consul") ---
  consul-1:
    image: hashicorp/consul:latest
    hostname: consul-1
    ports:
      - "8500:8500"
    command: >
      agent -server -ui -node=consul-node-1 -bootstrap-expect=3 -client=0.0.0.0
      -retry-join=consul-2 -retry-join=consul-3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 2s
      retries: 10
    profiles: [consul]

  consul-2:
    image: hashicorp/consul:latest
    hostname: consul-2
    command: >
      agent -server -node=consul-node-2 -bootstrap-expect=3 -client=0.0.0.0
      -retry-join=consul-1 -retry-join=consul-3
    depends_on: [consul-1]
    profiles: [consul]

  consul-3:
    image: hashicorp/consul:latest
    hostname: consul-3
    command: >
      agent -server -node=consul-node-3 -bootstrap-expect=3 -client=0.0.0.0
      -retry-join=consul-1 -retry-join=consul-2
    depends_on: [consul-1]
    profiles: [consul]

    # --- 2. Traefik 1 ---
  traefik-1:
    image: traefik:v3.2
    ports:
      - "9080:80"       # Porta pública Traefik 1
      - "8080:8080"     # Dashboard opcional
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      consul-1:
        condition: service_healthy
    profiles: [lb]

  # --- 3. Traefik 2 ---
  traefik-2:
    image: traefik:v3.2
    ports:
      - "9081:80"       # Porta pública Traefik 2
      - "8081:8080"     # Dashboard opcional
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      consul-1:
        condition: service_healthy
    profiles: [lb]

    # --- 2. APLICAÇÃO: SERVIDOR DE JOGO (PERFIL: "game", ESCALÁVEL) ---
  jokenpo-monolith:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    depends_on:
      consul-1:
        condition: service_healthy
    environment:
      - HEALTH_CHECK_PORT=8000
      - CONSUL_HTTP_ADDR=consul-1:8500
    deploy:
      replicas: 10   # Escalável via compose scale também
    profiles: [game]