# docker-compose.mixed-test.yml
services:
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    container_name: jokenpo-server-mixed-test
    ports:
      - "8080:8080"
      - "8081:8081/udp"

  bot-pack-opener:
    build:
      context: .
      # Todos os serviços de bot usam o mesmo Dockerfile
      dockerfile: ./cmd/bots/mixed-behavior/Dockerfile
    depends_on:
      - server
    environment:
      - BOT_ROLE=PACK_OPENER

  bot-pinger:
    build:
      context: .
      dockerfile: ./cmd/bots/mixed-behavior/Dockerfile
    depends_on:
      - server
    environment:
      - BOT_ROLE=PINGER

  bot-matchmaker:
    build:
      context: .
      dockerfile: ./cmd/bots/mixed-behavior/Dockerfile
    depends_on:
      - server
    environment:
      - BOT_ROLE=MATCHMAKER