# docker-compose.test.yml
version: '3.8'

services:
  # O serviço do servidor é praticamente o mesmo
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    container_name: jokenpo-server
    ports:
      - "8080:8080"
      - "8081:8081/udp"

  # O serviço do BOT não-interativo
  bot:
    build:
      context: .
      dockerfile: ./cmd/bot/Dockerfile
    depends_on:
      - server
    # Note que não precisamos de 'stdin_open' ou 'tty' aqui,
    # pois o bot não precisa de um terminal interativo.