services:
  server:
    build:
      context: ../backend/server
      # A partir do 'context', volte duas pastas e entre na pasta 'docker'
      dockerfile: ../../docker/server.Dockerfile
    container_name: go-server
    ports:
      - "8080:8080"
    networks:
      - pblnet

  client:
    build:
      context: ../backend/client
      # A lógica é a mesma para o client
      dockerfile: ../../docker/client.Dockerfile
    container_name: go-client
    depends_on:
      - server
    networks:
      - pblnet

networks:
  pblnet:
    driver: bridge